import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: {
    default:"Prince Educational Suppliy",
    template:"%s | Prince Educational Supply"
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/Company_Logo (1).ico" }],
  openGraph:{

  }
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
